### ISSUE TITLE
DLL can´t be loaded

### ISSUE THREAD

**Issue by LuemmelSec** [shuffle2/LpcAnalyzer#2]
Hey, I just built the DLL with VS2019.

Copied it to the Logic folder and added it via custom LLA.
However when I start Logic 2 (version 2.3.41 - the latest) it says:
Failed to load custom analyzer. Unable to load library.

![image](https://user-images.githubusercontent.com/58529760/145891887-0dc03276-6981-4ab0-a623-acb0cac097e7.png)

I also download the DLL from the other issue that is open - same result.
Any idea on how to troubleshoot from here?

Thanks.

**Comment by LuemmelSec** [comment]
This is the output from the build process:
![image](https://user-images.githubusercontent.com/58529760/145892657-1f396670-e5f2-4c24-9709-5ff506fb5af0.png)

**Comment by shuffle2** [comment]
hm, my guess is that when Logic loads from it's own `resources\Analyzers` dir, it expects the plugin to conform to the "v2" api. I notice that the builtin plugins export an extra symbol: `??4FrameV2@@QEAAAEAV0@AEBV0@@Z` (`public: class FrameV2 & FrameV2::operator=(class FrameV2 const &)`).

I'd suggest removing lpc_analyzer.dll from Logic's dir and pointing Logic at some other dir - such as LpcAnalyzer's `build\Analyzers` (don't worry, it will still load the builtin ones as well).

**Comment by shuffle2** [comment]
Logic's built-in analyzers have these symbols:
![image](https://user-images.githubusercontent.com/113063/145898892-0a77a0f7-0fc3-491f-a9b0-5bbe4bceb45e.png)
(the purple ones are imported from Logic's Analyzer.dll)
Part of the problem is that the Analyzer.dll which Saleae distributes as their "Analyzer SDK" is old and does not include those exports. While it would be possible to make a plugin use the newer Analyzer.dll and appear as a "v2" plugin, I'm not sure it's worth it. Honestly Saleae should just fix their embarrassing SDK.

**Comment by LuemmelSec** [comment]
Wow, thanks for your fast reply.
Moving the DLL to somewhere completely else didn´t fix the problem.
How did you manage to have Logic 2 load the libray then?

**Comment by shuffle2** [comment]
I actually tested this out locally now. Two things:
1. copying to Logic's own resources dir actually does work (altho the plugin does not have v2 interface)
2. your problem is likely that you've built 32bit dll instead of 64bit. please follow instructions README file closely (pass `amd64` or `x64` to `vcvarsall.bat` to setup x64 environment). I'll probably add a check in cmake to prevent building 32bit binary by accident..

**Comment by shuffle2** [comment]
how about this:

first, run `dumpbin /imports Analyzers\lpc_analyzer.dll` do you see `MSVCP140D.dll` ? If so, it means you built debug.
do this to build release:
```
cmake -DCMAKE_BUILD_TYPE=Release ..
cmake --build .
```
run `dumpbin /imports Analyzers\lpc_analyzer.dll` again. you should see `MSVCP140.dll` (without the D).

if that fixes the problem, it means you somehow installed VS without installing the debug redist

**Comment by LuemmelSec** [comment]
Oh man, you are my hero.
MSVCP140D.dll was there, so it build okay but as you said it was in Debug mode.
The DLL is now much smaller and could easily be loaded into Logic 2.

Thank you very very much.
I love this community and your immediate answers.
